language: ruby

services:
  - docker
  

cache:
  bundler: true
  directories:
    - $HOME/docker
    
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - yarn

script:
  - docker -v
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
  - ls -al /proc/sys/fs/binfmt_misc/
  - docker buildx create --use --name mybuilder
  - yarn run build
  - docker buildx ls
  - docker buildx build -t xiaodi93/ant-design:latest --platform linux/amd64,linux/arm64 . --push
  
