language: ruby
services:
  - docker
cache:
  bundler: true
  directories:
    - '$HOME/docker'
before_install:
  - openssl aes-256-cbc -K $encrypted_8848fde83ebf_key -iv $encrypted_8848fde83ebf_iv
    -in travis.enc -out ~/.ssh/travis -d
  - chmod 600  ~/.ssh/travis
  - yarn
addons:
  ssh_known_hosts: 47.56.158.125
before_deploy:
  - yarn run build
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t xiaodi93/ant-design:latest .
  - docker push xiaodi93/ant-design:latest
  - ssh -i ~/.ssh/travis root@47.56.158.125 "cd server;docker pull xiaodi93/ant-design:latest;docker-compose -f app.yaml up -d"

deploy:
  provider: releases
  on:
    repo: edenleung/think-ant-vue
    tags: true
