language: node_js

node_js:
  - 10.15.0
  
cache: yarn

before_install:
  - yarn
  
script:
  - yarn run build
  
after_script:
  - chmod 600 /home/travis/build/xiaodit/think-ant-vue/deploy/file
  - rsync -r /home/travis/build/xiaodit/think-ant-vue/public/* -e "ssh -o StrictHostKeyChecking=no -p ${XDPORT} -i /home/travis/build/xiaodit/think-ant-vue/deploy/file" ${XDUSER}@${XDHOST}:~/lnmp/workspace/ant/vue
