language: node_js

node_js:
  - 10.15.0
  
cache: yarn

before_install:
  - yarn
  - openssl aes-256-cbc -K $encrypted_908217f1fe77_key -iv $encrypted_908217f1fe77_iv -in privatekey.enc -out /home/travis/build/xiaodit/think-ant-vue/privatekey -d
  - chmod 600 /home/travis/build/xiaodit/think-ant-vue/privatekey
  - ssh-add /home/travis/build/xiaodit/think-ant-vue/privatekey
script:
  - yarn run build
  
after_script:
  - rsync -r /home/travis/build/xiaodit/think-ant-vue/dist/* -e "ssh -o StrictHostKeyChecking=no -i /home/travis/build/xiaodit/think-ant-vue/privatekey -p ${XDPORT}" ${XDUSER}@${XDHOST}:${XDPATH}
